dist: trusty
language: node_js
node_js:
  - '12'

os:
  - linux

jobs:
  include:
    - stage: install
      script: npm install
    - stage: test
      script: npm run test
    - stage: release
      script:
        - npx semantic-release
      if: branch = master
